sudo: false
language: java
install: mvn install -DskipTests=true
script: mvn test
jdk:
  - oraclejdk7
  - oraclejdk8
after_success:
  - mvn jacoco:report coveralls:report
# http://lint.travis-ci.org/ validator